[package]
name = "bookmarks"
version = "0.9.5"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-multipart = "0.6"
actix-web = "4.3"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rusqlite = { version = "0.29", features = ["bundled"] }
sailfish = "0.6"
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["macros", "formatting", "local-offset"] }
