[package]
name = "bookmarks"
version = "0.3.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.28", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.3"
actix-multipart = "0.6"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
chrono = "0.4"
tera = "1.18"
lazy_static = "1.4"
